import random

# ==========================================
# CẤU HÌNH QUY MÔ (LARGE SCALE)
# ==========================================
NUM_PATIENTS = 150
NUM_SURGEONS = 20
NUM_DAYS = 5
NUM_ROOMS = 6
DAY_MINUTES = 480 # 8 tiếng hành chính

# Tham số thời gian (Giữ nguyên như bài toán gốc)
# Type 1..10
DURATIONS = [60, 65, 30, 30, 90, 100, 160, 90, 65, 30]
PREP_TIMES = [10, 10, 10, 10, 10, 15, 15, 15, 15, 15]
REST_TIMES = [15, 15, 15, 15, 15, 30, 30, 20, 20, 10]

def generate_opl_data(filename="large_scale_150p.dat"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write("/*********************************************\n")
        f.write(f" * LARGE SCALE DATASET GENERATED BY PYTHON\n")
        f.write(f" * Patients: {NUM_PATIENTS}, Surgeons: {NUM_SURGEONS}, Rooms: {NUM_ROOMS}\n")
        f.write(f" *********************************************/\n\n")

        # 1. SETS
        # P = {1, 2, ..., 150}
        f.write(f"P = {{ {', '.join(str(i) for i in range(1, NUM_PATIENTS + 1))} }};\n")
        f.write(f"S = {{ {', '.join(str(i) for i in range(1, NUM_SURGEONS + 1))} }};\n")
        f.write(f"D = {{ {', '.join(str(i) for i in range(1, NUM_DAYS + 1))} }};\n")
        f.write(f"K = {{ {', '.join(str(i) for i in range(1, NUM_ROOMS + 1))} }};\n\n")
        
        f.write("SurgeryTypes = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};\n")
        
        # 2. PARAMETERS
        # wh array
        wh_str = ", ".join([str(DAY_MINUTES)] * NUM_DAYS)
        f.write(f"wh = [{wh_str}];\n\n")

        # Duration, Prep, Rest arrays
        f.write(f"DurationByType = [{', '.join(map(str, DURATIONS))}];\n")
        f.write(f"PrepType = [{', '.join(map(str, PREP_TIMES))}];\n")
        f.write(f"RestingTimeByType = [{', '.join(map(str, REST_TIMES))}];\n\n")

        # 3. PATIENT TYPES
        # Random loại phẫu thuật cho 150 bệnh nhân
        # Bias nhẹ: Các ca ngắn (Type 3,4,10) xuất hiện nhiều hơn để dễ lấp đầy lịch
        # Type 1-10 tương ứng index 0-9
        types = []
        for _ in range(NUM_PATIENTS):
            # Tỉ lệ random: Ca ngắn (30p) xác suất cao hơn ca dài (160p)
            t = random.choices(range(1, 11), weights=[10, 10, 15, 15, 10, 8, 5, 8, 10, 15])[0]
            types.append(t)
        
        f.write("PatientType = [\n")
        for i in range(0, NUM_PATIENTS, 20): # Xuống dòng mỗi 20 số cho đẹp
            chunk = types[i:i+20]
            f.write("  " + ", ".join(map(str, chunk)) + ("," if i+20 < NUM_PATIENTS else "") + "\n")
        f.write("];\n\n")

        # 4. AVAILABILITY (Avail[S][D])
        # Random: Bác sĩ nghỉ 1 ngày trong tuần (80% đi làm)
        avail_matrix = []
        f.write("Avail = [\n")
        for s in range(NUM_SURGEONS):
            # Tạo lịch ngẫu nhiên: 1 là đi làm, 0 là nghỉ
            row = [1 if random.random() < 0.85 else 0 for _ in range(NUM_DAYS)]
            avail_matrix.append(row)
            f.write("  [" + ", ".join(map(str, row)) + "]" + ("," if s < NUM_SURGEONS - 1 else "") + "\n")
        f.write("];\n\n")

        # 5. SKILLS (IsResponsible, IsAssistant1, IsAssistant2)
        # Giả định:
        # - S1-S10: Senior (Có thể làm Main)
        # - S11-S20: Junior (Chỉ làm Assist)
        
        # IsResponsible [S][Type][Day] -> 3D Matrix
        # Để đơn giản, kỹ năng không đổi theo ngày, copy cho 5 ngày
        f.write("// IsResponsible [Surgeon][Type][Day]\n")
        f.write("IsResponsible = [\n")
        
        for s in range(NUM_SURGEONS):
            f.write("  [ // Surgeon " + str(s+1) + "\n")
            
            # Xác định skill của bác sĩ này
            can_main = [0] * 10
            if s < 12: # 12 Bác sĩ đầu là Senior
                # Random mỗi ông làm main được 3-5 loại phẫu thuật
                my_skills = random.sample(range(10), k=random.randint(3, 6))
                for t_idx in my_skills:
                    can_main[t_idx] = 1
            
            # Viết ra 10 loại phẫu thuật, mỗi loại lặp lại 5 ngày
            for t in range(10):
                # Dòng này: [1, 1, 1, 1, 1] hoặc [0, 0, 0, 0, 0]
                day_skills = [can_main[t]] * NUM_DAYS
                f.write("    [" + ", ".join(map(str, day_skills)) + "]" + ("," if t < 9 else "") + "\n")
            
            f.write("  ]" + ("," if s < NUM_SURGEONS - 1 else "") + "\n")
        f.write("];\n\n")

        # IsAssistant1 [S][Type][Day] -> 3D Matrix
        # Ai cũng có thể làm Assistant1 cho hầu hết các loại (trừ khi quá khó)
        f.write("// IsAssistant1 [Surgeon][Type][Day]\n")
        f.write("IsAssistant1 = [\n")
        for s in range(NUM_SURGEONS):
            f.write("  [ // Surgeon " + str(s+1) + "\n")
            can_asst = [1] * 10 # Mặc định làm được hết
            
            # Random bỏ bớt 1-2 loại quá khó với Junior
            if s >= 12: # Junior
                unskilled = random.sample(range(10), k=2)
                for t_idx in unskilled: can_asst[t_idx] = 0
            
            for t in range(10):
                day_skills = [can_asst[t]] * NUM_DAYS
                f.write("    [" + ", ".join(map(str, day_skills)) + "]" + ("," if t < 9 else "") + "\n")
            f.write("  ]" + ("," if s < NUM_SURGEONS - 1 else "") + "\n")
        f.write("];\n\n")

        # IsAssistant2 [S][Day] -> 2D Matrix
        # Tất cả Junior (S11-S20) đều làm được Asst2 mọi ngày
        # Senior thì ít làm Asst2 hơn
        f.write("// IsAssistant2 [Surgeon][Day]\n")
        f.write("IsAssistant2 = [\n")
        for s in range(NUM_SURGEONS):
            if s >= 10: # Junior -> Luôn sẵn sàng làm phụ 2
                row = [1] * NUM_DAYS
            else: # Senior -> Không làm phụ 2
                row = [0] * NUM_DAYS
            f.write("  [" + ", ".join(map(str, row)) + "]" + ("," if s < NUM_SURGEONS - 1 else "") + "\n")
        f.write("];\n")

    print(f"Đã tạo file dữ liệu mẫu: {filename}")
    print(f"- Quy mô: {NUM_PATIENTS} bệnh nhân, {NUM_SURGEONS} bác sĩ, {NUM_ROOMS} phòng mổ.")

if __name__ == "__main__":
    generate_opl_data()